<a href="https://colab.research.google.com/github/Binshadcs/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [34]:
import numpy as np
array = np.random.randint(10, size=(3,3))
print(array)

[[5 2 4]
 [3 9 0]
 [2 3 4]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [46]:
list = [[1,2,3,6],[4,5,6,6],[7,8,9,1],[4,5,6,9]]
array1 = np.array(list, dtype=int)
print(array1)
print("--------------------------")
shaped1 = array1.reshape(2,8)
print(shaped1)

[[1 2 3 6]
 [4 5 6 6]
 [7 8 9 1]
 [4 5 6 9]]
--------------------------
[[1 2 3 6 4 5 6 6]
 [7 8 9 1 4 5 6 9]]


In [47]:
array2 = np.random.randint(10, size=(4,4))
print(array2)
print("--------------------------")
shaped2 = array2.reshape(2,8)
print(shaped2)

[[4 8 6 2]
 [5 1 4 8]
 [6 6 4 9]
 [0 6 8 6]]
--------------------------
[[4 8 6 2 5 1 4 8]
 [6 6 4 9 0 6 8 6]]


In [49]:
stacked = np.hstack((shaped1,shaped2))
print(stacked)

[[1 2 3 6 4 5 6 6 4 8 6 2 5 1 4 8]
 [7 8 9 1 4 5 6 9 6 6 4 9 0 6 8 6]]


In [50]:
stacked = np.vstack((shaped1,shaped2))
print(stacked)

[[1 2 3 6 4 5 6 6]
 [7 8 9 1 4 5 6 9]
 [4 8 6 2 5 1 4 8]
 [6 6 4 9 0 6 8 6]]
