<a href="https://colab.research.google.com/github/Binshadcs/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [4]:
import numpy as np
array = np.random.randint(10, size=(3,3))
print(array)

[[8 2 2]
 [7 0 7]
 [9 5 1]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [18]:
list = [[1,2,3,6],[4,5,6,6],[7,8,9,1],[4,5,6,9]]
array1 = np.array(list, dtype=int)
print(array1)

[[1 2 3 6]
 [4 5 6 6]
 [7 8 9 1]
 [4 5 6 9]]


In [21]:
array2 = array1.reshape(2,8)
print(array2)

[[1 2 3 6 4 5 6 6]
 [7 8 9 1 4 5 6 9]]
9


In [20]:
array3 = array1.reshape(8,2)
print(array3)

[[1 2]
 [3 6]
 [4 5]
 [6 6]
 [7 8]
 [9 1]
 [4 5]
 [6 9]]
