<a href="https://colab.research.google.com/github/Binshadcs/Learn.py/blob/main/TASK_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create two arrays, one containing elements [1,2], [3,4] and another containing elements [8,18] Now find the solution for this linear equation.

In [1]:

import numpy as np
a=np.array ([[1,2],[3,4]])
print (a)
b=np.array ([[8],[18]])
print (b)
x=np.linalg.solve(a,b)
print (x)#please type your answer below this line.

[[1 2]
 [3 4]]
[[ 8]
 [18]]
[[2.]
 [3.]]


2. Create an array containing elements [2, 3, 4]. Now find the sin,cos,tan values of this array elements.

In [2]:
#please type your answer below this line.
import numpy as np
a=np.array([2,3,4])
print (a)
x=np.sin(a)
print (x)
y=np.cos(a)
print (y)
z=np.tan(a)
print (z)

[2 3 4]
[ 0.90929743  0.14112001 -0.7568025 ]
[-0.41614684 -0.9899925  -0.65364362]
[-2.18503986 -0.14254654  1.15782128]


3. Given b=[5,6], then find,

  a) 2sinb
  b) 2cos3b
  c) 4tan2b

In [4]:
#please type your answer below this line.
import numpy as np
b=np.array([5,6])
print(b)

a=2*np.sin(b)
print(a)

c=2*np.cos (3*b)
print(c)

d=4*np.tan(2*b)
print(d)

[5 6]
[-1.91784855 -0.558831  ]
[-1.51937583  1.32063342]
[ 2.59344331 -2.54343971]


In [5]:
B = [5,6]

a = 2*np.sin(B)
print(a)

b = 2*np.cos(3*B)
print('\n',b)

c = 4*np.tan(2*b)
print('\n',c)

[-1.91784855 -0.558831  ]

 [0.56732437 1.92034057 0.56732437 1.92034057 0.56732437 1.92034057]

 [8.58216642 3.3629256  8.58216642 3.3629256  8.58216642 3.3629256 ]


In [6]:
import numpy as np
 
ar=np.array([5,6])
b1=3*ar
c1=2*ar
 
sin_value=np.sin(ar)
cos_value=np.cos(b1)
tan_value=np.tan(c1)
 
a=2*sin_value
b=2*cos_value
c=4*tan_value
 
print("2sinb = ",a)
print("2cos3b = ",b)
print("4tan2b = ",c)

2sinb =  [-1.91784855 -0.558831  ]
2cos3b =  [-1.51937583  1.32063342]
4tan2b =  [ 2.59344331 -2.54343971]
